version: "3"

services:
  database:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: ${PortfolioDbPassword:?error}
    ports:
      - "1500:1433"

  portfolioweb:
    depends_on:
      - database
    image: portfolio
    build:
      context: .
      dockerfile: PortfolioWeb/Dockerfile
    restart: on-failure
    environment:
      ConnectionStrings__Portfolio: ${PortfolioDbConnectionString:?error}
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "80:8080"