name: Build and Deploy to Nomad

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from .csproj
        id: extract_version
        run: |
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" Portfolio.csproj)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Build Docker Image
        run: |
          docker build -t cimran2001/portfolio:$VERSION .
          docker tag cimran2001/portfolio:$VERSION cimran2001/portfolio:latest

      - name: Push Docker Image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push cimran2001/portfolio:$VERSION
          docker push cimran2001/portfolio:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace Version in Nomad Job File
        run: |
          sed -i "s|image = \"cimran2001/portfolio:latest\"|image = \"cimran2001/portfolio:$VERSION\"|g" nomad/portfolio.nomad

      - name: Deploy to Nomad
        env:
          NOMAD_ADDR: ${{ secrets.NOMAD_ADDR }}
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
        run: |
          curl --request POST --header "X-Nomad-Token: $NOMAD_TOKEN" --data-binary @nomad/portfolio.nomad "$NOMAD_ADDR/v1/jobs"
