name: Build and Deploy to Nomad

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch `portfolio.nomad` from server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP:/path/to/portfolio.nomad portfolio.nomad

      - name: Update Docker Image Version in Nomad File
        run: |
          sed -i "s|image = \"cimran2001/portfolio:latest\"|image = \"cimran2001/portfolio:$VERSION\"|g" portfolio.nomad
          echo "Updated portfolio.nomad:"
          cat portfolio.nomad

      - name: Deploy to Nomad via cURL
        env:
          NOMAD_ADDR: ${{ secrets.NOMAD_ADDR }}
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
        run: |
          curl --request POST --header "X-Nomad-Token: $NOMAD_TOKEN" --data-binary @portfolio.nomad "$NOMAD_ADDR/v1/jobs"
