# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      pull-requests: read

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get changed files in the docs folder
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        files: Portfolio/**/*.{cs,cshtml,json,js,css}
        
    - name: Debug changed files
      run: |
        echo "Any changed: ${{ steps.changed-files.outputs.any_changed }}"
        echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"

    - name: Extract version from .csproj
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" Portfolio/Portfolio.csproj)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Extracted version: $VERSION"

    - uses: mukunku/tag-exists-action@v1.4.0
      if: steps.changed-files.outputs.any_changed == 'true'
      id: check-tag
      with:
        tag: "v$VERSION"
        
    - name: Check version
      if: steps.changed-files.outputs.any_changed == 'true' && steps.check-tag.outputs.exists == 'true'
      run: |
        echo "Version $VERSION already exists"
        exit 1

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
