# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      pull-requests: read

    steps:
    - uses: actions/checkout@v4

    - name: Get changed files in the docs folder
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        files: Portfolio/**/*.{cs,cshtml,json,js,css}
        
    - name: Debug changed files
      run: |
        echo "Any changed: ${{ steps.changed-files.outputs.any_changed }}"
        echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"

    - name: Extract version from .csproj
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" Portfolio/Portfolio.csproj)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Extracted version: $VERSION"

    - name: Check if tag exists
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        echo "Checking if tag v$VERSION exists..."
        git show-ref --tags --verify --quiet "refs/tags/$VERSION" 
        exit_code=$?
        echo ${exit_code}
        if [[ $exit_code -eq 0 ]]; then
          echo "Version $VERSION exists"
        else
          echo "Version $VERSION does not exist"
        fi

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
